// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVz3jvHNrKaubRcEVeXQX06dXO8fCw6zA',
    appId: '1:1020172078945:web:9ad7825c311b25a960bf20',
    messagingSenderId: '1020172078945',
    projectId: 'siakmhs-2a90b',
    authDomain: 'siakmhs-2a90b.firebaseapp.com',
    storageBucket: 'siakmhs-2a90b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWg9G7PoccPhXSVg58GiCV3vM1PzEb-5A',
    appId: '1:1020172078945:android:f70e9f418565174a60bf20',
    messagingSenderId: '1020172078945',
    projectId: 'siakmhs-2a90b',
    storageBucket: 'siakmhs-2a90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmFiFmuBhb1CgH-Eiw_0xbaNxt8RKTqKQ',
    appId: '1:1020172078945:ios:b628a9a52653982960bf20',
    messagingSenderId: '1020172078945',
    projectId: 'siakmhs-2a90b',
    storageBucket: 'siakmhs-2a90b.appspot.com',
    iosBundleId: 'com.example.siakmhs10012100052',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmFiFmuBhb1CgH-Eiw_0xbaNxt8RKTqKQ',
    appId: '1:1020172078945:ios:8cd0a75f1d4b846060bf20',
    messagingSenderId: '1020172078945',
    projectId: 'siakmhs-2a90b',
    storageBucket: 'siakmhs-2a90b.appspot.com',
    iosBundleId: 'com.example.siakmhs10012100052.RunnerTests',
  );
}
